export let CANADA_CITIES = {
    "AB": [
        "Airdrie",
        "Beaumont",
        "Brooks",
        "Calgary",
        "Chestermere",
        "Cold Lake",
        "Edmonton",
        "Fort Saskatchewan",
        "Grande Prairie",
        "Lacombe",
        "Leduc",
        "Lethbridge",
        "Lloydminster",
        "Medicine Hat",
        "Red Deer",
        "Spruce Grove",
        "St. Albert",
        "Wetaskiwin"
    ],
    "BC": [
        "Abbotsford",
        "Armstrong",
        "Burnaby",
        "Campbell River",
        "Castlegar",
        "Chilliwack",
        "Colwood",
        "Coquitlam",
        "Courtenay",
        "Cranbrook",
        "Dawson Creek",
        "Delta",
        "Duncan",
        "Enderby",
        "Fernie",
        "Fort St. John",
        "Grand Forks",
        "Greenwood",
        "Kamloops",
        "Kelowna",
        "Kimberley",
        "Langford",
        "Maple Ridge",
        "Merritt",
        "Mission",
        "Nanaimo",
        "Nelson",
        "New Westmenster",
        "North Vancouver",
        "Parksville",
        "Penticton",
        "Pitt Meadows",
        "Port Alberni",
        "Port Coquitlam",
        "Port Moody",
        "Powell River",
        "Prince George",
        "Prince Rupert",
        "Quesnel",
        "Revelstoke",
        "Richmond",
        "Rossland",
        "Salmon Arm",
        "Surrey",
        "Terrace",
        "Trail",
        "Vancouver",
        "Vernon",
        "Victoria",
        "West Kelowna",
        "White Rock",
        "Williams Lake"
    ],
    "MB": [
        "Brandon",
        "Dauphin",
        "Flin Flon",
        "Morden",
        "Portage la Prairie",
        "Selkirk",
        "Steinbach",
        "Thompson",
        "Winkler",
        "Winnipeg"
    ],
    "NB": [
        "Bathurst",
        "Campbellton",
        "Dieppe",
        "Edmundston",
        "Fredericton",
        "Miramichi",
        "Moncton",
        "Saint John"
    ],
    "NL": [
        "Corner Brook",
        "Mount Pearl",
        "St. John's"
    ],
    "NT": [
        "Yellowknife"
    ],
    "NS": [
        "Halifax",
        "Sydney",
        "Dartmouth"
    ],
    "NU": [
        "Iqaluit"
    ],
    "ON": [
        "Barrie",
        "Belleville",
        "Brampton",
        "Brant",
        "Brantford",
        "Brockville",
        "Burlington",
        "Cambridge",
        "Clarence-Rockland",
        "Cornwall",
        "Dryden",
        "Elliot Lake",
        "Greater Sudbury",
        "Guelph",
        "Haldimand County",
        "Hamilton",
        "Kawartha Lakes",
        "Kenora",
        "Kingston",
        "Kitchener",
        "London",
        "Markham",
        "Mississauga",
        "Niagara Falls",
        "Norfolk County",
        "North Bay",
        "Orillia",
        "Oshawa",
        "Ottawa",
        "Owen Sound",
        "Pembroke",
        "Peterborough",
        "Pickering",
        "Port Colborne",
        "Prince Edward County",
        "Quinte West",
        "Richmond Hill",
        "Sarnia",
        "Sault Ste. Marie",
        "St. Catharines",
        "St. Thomas",
        "Stratford",
        "Temiskaming Shores",
        "Thorold",
        "Thunder Bay",
        "Timmins",
        "Toronto",
        "Vaughan",
        "Waterloo",
        "Welland",
        "Windsor",
        "Woodstock"
    ],
    "PE": [
        "Charlottetown",
        "Summerside"
    ],
    "QC": [
        "Acton Vale",
        "Alma",
        "Amos",
        "Amqui",
        "Baie-Comeau",
        "Baie-D'Urfé",
        "Baie-Saint-Paul",
        "Barkmere",
        "Beaconsfield",
        "Beauceville",
        "Beauharnois",
        "Beaupré",
        "Bécancour",
        "Bedford",
        "Belleterre",
        "Beloeil",
        "Berthierville",
        "Blainville",
        "Boisbriand",
        "Bois-des-Filion",
        "Bonaventure",
        "Boucherville",
        "Lac-Brome",
        "Bromont",
        "Brossard",
        "Brownsburg-Chatham",
        "Candiac",
        "Cap-Chat",
        "Cap-Santé",
        "Carignan",
        "Carleton-sur-Mer",
        "Causapscal",
        "Chambly",
        "Chandler",
        "Chapais",
        "Charlemagne",
        "Châteauguay",
        "Château-Richer",
        "Chibougamau",
        "Clermont",
        "Coaticook",
        "Contrecoeur",
        "Cookshire-Eaton",
        "Côte Sain-Luc",
        "Coteau-du-lac",
        "Cowansville",
        "Danville",
        "Daveluyville",
        "Dégelis",
        "Delson",
        "Desbiens",
        "Deux-Montagnes",
        "Disraeli",
        "Dolbeau-Mistassini",
        "Dollard-des-Ormeaux",
        "Donnacona",
        "Dorval",
        "Drummondville",
        "Dunham",
        "Duparquet",
        "East Angus",
        "Estérel",
        "Farnham",
        "Fermont",
        "Forestville",
        "Fossambault-sur-le-Lac",
        "Gaspé",
        "Gatineau",
        "Gracefield",
        "Granby",
        "Grande-Rivière",
        "Hampstead",
        "Hudson",
        "Huntingdon",
        "Joliette",
        "Kingsey Falls",
        "Kirkland",
        "La Malbaie",
        "La Pocatière",
        "La Prairie",
        "La Sarre",
        "La Tuque",
        "Lac-Delage",
        "Lachute",
        "Lac-Mégantic",
        "Lac-Saint-Joseph",
        "Lac-Sergent",
        "L'Ancienne-Lorette",
        "L'Assomption",
        "Laval",
        "Lavaltrie",
        "Lebel-sur-Quévillon",
        "L'Épiphanie",
        "Léry",
        "Lévis",
        "L'Île-Cadieux",
        "L'Île-Dorval",
        "L'Île-Perrot",
        "Longueuil",
        "Lorraine",
        "Louiseville",
        "Macamic",
        "Magog",
        "Malartic",
        "Maniwaki",
        "Marieville",
        "Mascouche",
        "Matagami",
        "Matane",
        "Mercier",
        "Métabetchouan–Lac-à-la-Croix",
        "Métis-sur-Mer",
        "Mirabel",
        "Mont-Joli",
        "Mont-Laurier",
        "Montmagny",
        "Montreal",
        "Montreal West",
        "Montréal-Est",
        "Mont-Saint-Hilaire",
        "Mont-Tremblant",
        "Mount Royal",
        "Murdochville",
        "Neuville",
        "New Richmond",
        "Nicolet",
        "Normandin",
        "Notre-Dame-de-l'Île-Perrot",
        "Notre-Dame-des-Prairies",
        "Otterburn Park",
        "Paspébiac",
        "Percé",
        "Pincourt",
        "Plessisville",
        "Pohénégamook",
        "Pointe-Claire",
        "Pont-Rouge",
        "Port-Cartier",
        "Portneuf",
        "Prévost",
        "Princeville",
        "Québec",
        "Repentigny",
        "Richelieu",
        "Richmond",
        "Rigaud",
        "Rimouski",
        "Rivière-du-Loup",
        "Rivière-Rouge",
        "Roberval",
        "Rosemère",
        "Rouyn-Noranda",
        "Saguenay",
        "Saint-Amable",
        "Saint-Augustin-de-Desmaures",
        "Saint-Basile",
        "Saint-Basile-le-Grand",
        "Saint-Bruno-de-Montarville",
        "Saint-Césaire",
        "Saint-Charles-Borromée",
        "Saint-Colomban",
        "Saint-Constant",
        "Sainte-Adèle",
        "Sainte-Agathe-des-Monts",
        "Sainte-Anne-de-Beaupré",
        "Sainte-Anne-de-Bellevue",
        "Sainte-Anne-des-Monts",
        "Sainte-Anne-des-Plaines",
        "Sainte-Catherine",
        "Sainte-Catherine-de-la-Jacques-Cartier",
        "Sainte-Julie",
        "Sainte-Marguerite-du-Lac-Masson",
        "Sainte-Marie",
        "Sainte-Marthe-sur-le-Lac",
        "Sainte-Thérèse",
        "Saint-Eustache",
        "Saint-Félicien",
        "Saint-Gabriel",
        "Saint-Georges",
        "Saint-Hyacinthe",
        "Saint-Jean-sur-Richelieu",
        "Saint-Jérôme",
        "Saint-Joseph-de-Beauce",
        "Saint-Joseph-de-Sorel",
        "Saint-Lambert",
        "Saint-Lazare",
        "Saint-Lin–Laurentides",
        "Saint-Marc-des-Carrières",
        "Saint-Ours",
        "Saint-Pamphile",
        "Saint-Pascal",
        "Saint-Philippe",
        "Saint-Pie",
        "Saint-Raymond",
        "Saint-Rémi",
        "Saint-Sauveur",
        "Saint-Tite",
        "Salaberry-de-Valleyfield",
        "Schefferville",
        "Scotstown",
        "Senneterre",
        "Sept-Îles",
        "Shannon",
        "Shawinigan",
        "Sherbrooke",
        "Sorel-Tracy",
        "Stanstead",
        "Sutton",
        "Témiscaming",
        "Témiscouata-sur-le-Lac",
        "Terrebonne",
        "Thetford Mines",
        "Thurso",
        "Trois-Pistoles",
        "Trois-Rivières",
        "Valcourt",
        "Val-d'Or",
        "Val-des-Sources",
        "Varennes",
        "Vaudreuil-Dorion",
        "Victoriaville",
        "Ville-Marie",
        "Warwick",
        "Waterloo",
        "Waterville",
        "Westmount",
        "Windsor"
    ],
    "SK": [
        "Estevan",
        "Flin Flon",
        "Humboldt",
        "Lloydminster",
        "Martensville",
        "Meadow Lake",
        "Melfort",
        "Melville",
        "Moose Jaw",
        "North Battleford",
        "Prince Albert",
        "Regina",
        "Saskatoon",
        "Swift Current",
        "Warman",
        "Weyburn",
        "Yorkton"
    ],
    "YT": [
        "Whitehorse"
    ]


}