export let USA_STATES = [
    { 'Key': 'AL', 'Value': 'Alabama' },
    { 'Key': 'AK', 'Value': 'Alaska' },
    { 'Key': 'AZ', 'Value': 'Arizona' },
    { 'Key': 'AR', 'Value': 'Arkansas' },
    { 'Key': 'CA', 'Value': 'California' },
    { 'Key': 'CO', 'Value': 'Colorado' },
    { 'Key': 'CT', 'Value': 'Connecticut' },
    { 'Key': 'DE', 'Value': 'Delaware' },
    { 'Key': 'DC', 'Value': 'District of Columbia' },
    { 'Key': 'FL', 'Value': 'Florida' },
    { 'Key': 'GA', 'Value': 'Georgia' },
    { 'Key': 'HI', 'Value': 'Hawaii' },
    { 'Key': 'ID', 'Value': 'Idaho' },
    { 'Key': 'IL', 'Value': 'Illinois' },
    { 'Key': 'IN', 'Value': 'Indiana' },
    { 'Key': 'IA', 'Value': 'Iowa' },
    { 'Key': 'KS', 'Value': 'Kansas' },
    { 'Key': 'KY', 'Value': 'Kentucky' },
    { 'Key': 'LA', 'Value': 'Louisiana' },
    { 'Key': 'ME', 'Value': 'Maine' },
    { 'Key': 'MD', 'Value': 'Maryland' },
    { 'Key': 'MA', 'Value': 'Massachusetts' },
    { 'Key': 'MI', 'Value': 'Michigan' },
    { 'Key': 'MN', 'Value': 'Minnesota' },
    { 'Key': 'MS', 'Value': 'Mississippi' },
    { 'Key': 'MO', 'Value': 'Missouri' },
    { 'Key': 'MT', 'Value': 'Montana' },
    { 'Key': 'NE', 'Value': 'Nebraska' },
    { 'Key': 'NV', 'Value': 'Nevada' },
    { 'Key': 'NH', 'Value': 'New Hampshire' },
    { 'Key': 'NJ', 'Value': 'New Jersey' },
    { 'Key': 'NM', 'Value': 'New Mexico' },
    { 'Key': 'NY', 'Value': 'New York' },
    { 'Key': 'NC', 'Value': 'North Carolina' },
    { 'Key': 'ND', 'Value': 'North Dakota' },
    { 'Key': 'OH', 'Value': 'Ohio' },
    { 'Key': 'OK', 'Value': 'Oklahoma' },
    { 'Key': 'OR', 'Value': 'Oregon' },
    { 'Key': 'PA', 'Value': 'Pennsylvania' },
    { 'Key': 'PR', 'Value': 'Puerto Rico' },
    { 'Key': 'RI', 'Value': 'Rhode Island' },
    { 'Key': 'SC', 'Value': 'South Carolina' },
    { 'Key': 'SD', 'Value': 'South Dakota' },
    { 'Key': 'TN', 'Value': 'Tennessee' },
    { 'Key': 'TX', 'Value': 'Texas' },
    { 'Key': 'UT', 'Value': 'Utah' },
    { 'Key': 'VT', 'Value': 'Vermont' },
    { 'Key': 'VA', 'Value': 'Virginia' },
    { 'Key': 'VI', 'Value': 'Virgin Islands' },
    { 'Key': 'WA', 'Value': 'Washington' },
    { 'Key': 'WV', 'Value': 'West Virginia' },
    { 'Key': 'WI', 'Value': 'Wisconsin' },
    { 'Key': 'WY', 'Value': 'Wyoming' },
];